defaults: &defaults
  docker:
    - image: 552172703831.dkr.ecr.us-west-2.amazonaws.com/infra-tools:latest
  working_directory: ~/app
  environment:
    - AWS_REGION: us-west-2
    - AWS_PREFIX: jibakurei
    - AMI_NAME: amzn2-base

version: 2
jobs:
  wf_first_job:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Checking Chef
          command: |
            which chef
            chef --version
            echo ''
            which ruby
            ruby --version


  wf_second_job:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Dummy Job
          command: echo "This is the second job of the workflow"

workflows:
  version: 2
  commit:
    jobs:
      - wf_first_job
      - wf_second_job:
          filters:
            branches:
              only:
                - master







