defaults: &defaults
  docker:
    - image: centos:latest
  working_directory: ~/app
  environment:
    - AWS_REGION: us-west-2
    - AWS_PREFIX: jibakurei
    - AMI_NAME: amzn2-base

version: 2
jobs:
  wf_first_job:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: 1st Job Run
          command: echo "Success" > firstJob.txt

  wf_second_job:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Packer Build
          command: ls -la /root/app

workflows:
  version: 2
  commit:
    jobs:
      - wf_first_job
      - wf_second_job:
          filters:
            branches:
              only:
                - master







